# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from enum import Enum


class Order(Enum):
    created = 'created'
    last_emailed = 'last_emailed'
    seen = 'seen'
    username = 'username'
    email = 'email'
    trust_level = 'trust_level'
    days_visited = 'days_visited'
    posts_read = 'posts_read'
    topics_viewed = 'topics_viewed'
    posts = 'posts'
    read_time = 'read_time'


class Asc(Enum):
    true = 'true'


class Flag(Enum):
    active = 'active'
    new = 'new'
    staff = 'staff'
    suspended = 'suspended'
    blocked = 'blocked'
    suspect = 'suspect'


class IncludeSubcategories(Enum):
    boolean_True = True


class Period(Enum):
    daily = 'daily'
    weekly = 'weekly'
    monthly = 'monthly'
    quarterly = 'quarterly'
    yearly = 'yearly'
    all = 'all'


class Order2(Enum):
    likes_received = 'likes_received'
    likes_given = 'likes_given'
    topic_count = 'topic_count'
    post_count = 'post_count'
    topics_entered = 'topics_entered'
    posts_read = 'posts_read'
    days_visited = 'days_visited'
