# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: str = Field(..., examples=['OK'])
