# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Triggers(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    none: int
    post_action: int
    post_revision: int
    trust_level_change: int
    user_change: int


class AdminBadges(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    badge_grouping_ids: List
    badge_ids: List
    badge_type_ids: List
    protected_system_fields: List
    triggers: Triggers


class BadgeGrouping(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Optional[str] = None
    id: int
    name: str
    position: int
    system: bool


class BadgeType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    name: str
    sort_order: int


class Badge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allow_title: bool
    auto_revoke: bool
    badge_grouping_id: int
    badge_type_id: int
    description: str
    enabled: bool
    grant_count: int
    i18n_name: Optional[str] = None
    icon: str
    id: int
    image_url: Optional[str] = None
    listable: bool
    long_description: str
    manually_grantable: bool
    multiple_grant: bool
    name: str
    query: Optional[str] = None
    show_posts: bool
    slug: str
    system: bool
    target_posts: bool
    trigger: Optional[int] = None


class JsonGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admin_badges: AdminBadges
    badge_groupings: List[BadgeGrouping]
    badge_types: List[BadgeType]
    badges: List[Badge]


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    badge_type_id: int = Field(
        ...,
        description='The ID for the badge type. 1 for Gold, 2 for Silver,\n3 for Bronze.',
    )
    name: str = Field(..., description='The name for the new badge.')


class BadgeModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allow_title: bool
    auto_revoke: bool
    badge_grouping_id: int
    badge_type_id: int
    description: str
    enabled: bool
    grant_count: int
    icon: str
    id: int
    image_url: Optional[str] = None
    listable: bool
    long_description: str
    manually_grantable: bool
    multiple_grant: bool
    name: str
    query: Optional[str] = None
    show_posts: bool
    slug: str
    system: bool
    target_posts: bool
    trigger: Optional[str] = None


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    badge: BadgeModel
    badge_types: List[BadgeType]
