# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class JsonPutRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Optional[str] = Field(
        None, description='Will send an email with this message when present'
    )
    post_action: Optional[str] = Field(None, examples=['delete'])
    reason: str
    suspend_until: str = Field(..., examples=['2121-02-22'])


class SuspendedBy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avatar_template: str
    id: int
    name: str
    username: str


class Suspension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    full_suspend_reason: str
    suspend_reason: str
    suspended_at: str
    suspended_by: SuspendedBy
    suspended_till: str


class JsonPutResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    suspension: Suspension
