# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Group(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    automatic_membership_email_domains: Optional[str] = Field(
        None, description='pipe|separated'
    )
    bio_raw: Optional[str] = Field(None, description='About Group')
    default_notification_level: Optional[int] = None
    flair_bg_color: Optional[str] = None
    flair_icon: Optional[str] = None
    flair_upload_id: Optional[int] = None
    full_name: Optional[str] = None
    muted_category_ids: Optional[List[int]] = None
    name: str
    owner_usernames: Optional[str] = Field(None, description='comma,separated')
    primary_group: Optional[bool] = None
    public_admission: Optional[bool] = None
    public_exit: Optional[bool] = None
    regular_category_ids: Optional[List[int]] = None
    tracking_category_ids: Optional[List[int]] = None
    usernames: Optional[str] = Field(None, description='comma,separated')
    visibility_level: Optional[int] = None
    watching_category_ids: Optional[List[int]] = None
    watching_first_post_category_ids: Optional[List[int]] = None


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    group: Group


class BasicGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allow_membership_requests: bool
    automatic: bool
    bio_cooked: Optional[str] = None
    bio_excerpt: Optional[str] = None
    bio_raw: Optional[str] = None
    can_admin_group: bool
    can_edit_group: Optional[bool] = None
    can_see_members: bool
    default_notification_level: int
    flair_bg_color: Optional[str] = None
    flair_color: Optional[str] = None
    flair_url: Optional[str] = None
    full_name: Optional[str] = None
    grant_trust_level: Optional[str] = None
    has_messages: bool
    id: int
    incoming_email: Optional[str] = None
    members_visibility_level: int
    membership_request_template: Optional[str] = None
    mentionable_level: int
    messageable_level: int
    name: str
    primary_group: bool
    public_admission: bool
    public_exit: bool
    publish_read_state: bool
    title: Optional[str] = None
    user_count: int
    visibility_level: int


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    basic_group: BasicGroup
