# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field, RootModel


class JsonGetResponseItem(BaseModel):
    filename: str
    last_modified: str
    size: int


class JsonGetResponse(RootModel[List[JsonGetResponseItem]]):
    root: List[JsonGetResponseItem] = Field(..., min_length=1)


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    with_uploads: bool


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: str = Field(..., examples=['OK'])
