# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class JsonGetResponseItem(BaseModel):
    active: bool
    admin: bool
    avatar_template: str
    created_at: str
    created_at_age: Optional[float] = None
    days_visited: int
    email: Optional[str] = None
    flag_level: int
    id: int
    last_emailed_age: Optional[float] = None
    last_emailed_at: Optional[str] = None
    last_seen_age: Optional[float] = None
    last_seen_at: Optional[str] = None
    manual_locked_trust_level: Optional[str] = None
    moderator: bool
    name: Optional[str] = None
    post_count: int
    posts_read_count: int
    secondary_emails: Optional[List] = None
    staged: bool
    time_read: int
    title: Optional[str] = None
    topics_entered: int
    trust_level: int
    username: str


class JsonGetResponse(RootModel[List[JsonGetResponseItem]]):
    root: List[JsonGetResponseItem] = Field(..., min_length=1)
