# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class JsonPutRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Optional[str] = Field(
        None, description='Will send an email with this message when present'
    )
    post_action: Optional[str] = Field(None, examples=['delete'])
    reason: Optional[str] = None
    silenced_till: Optional[str] = Field(None, examples=['2022-06-01T08:00:00.000Z'])


class SilencedBy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avatar_template: str
    id: int
    name: str
    username: str


class Silence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    silence_reason: str
    silenced: bool
    silenced_at: str
    silenced_by: SilencedBy
    silenced_till: str


class JsonPutResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    silence: Silence
