# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class User(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avatar_template: str
    id: int
    name: Optional[str] = None
    title: Optional[str] = None
    username: str


class DirectoryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    days_visited: int
    id: int
    likes_given: int
    likes_received: int
    post_count: int
    posts_read: int
    topic_count: int
    topics_entered: int
    user: User


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    last_updated_at: Optional[str] = None
    load_more_directory_items: str
    total_rows_directory_items: int


class JsonGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    directory_items: List[DirectoryItem]
    meta: Meta
