# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Extras(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type_filters: List


class Group(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allow_membership_requests: bool
    automatic: bool
    bio_cooked: Optional[str] = None
    bio_excerpt: Optional[str] = None
    bio_raw: Optional[str] = None
    can_admin_group: bool
    can_edit_group: Optional[bool] = None
    can_see_members: bool
    default_notification_level: int
    display_name: str
    flair_bg_color: Optional[str] = None
    flair_color: Optional[str] = None
    flair_url: Optional[str] = None
    full_name: Optional[str] = None
    grant_trust_level: Optional[str] = None
    has_messages: bool
    id: int
    incoming_email: Optional[str] = None
    is_group_owner: Optional[bool] = None
    is_group_user: Optional[bool] = None
    members_visibility_level: int
    membership_request_template: Optional[str] = None
    mentionable_level: int
    messageable_level: int
    name: str
    primary_group: bool
    public_admission: bool
    public_exit: bool
    publish_read_state: bool
    title: Optional[str] = None
    user_count: int
    visibility_level: int


class JsonGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extras: Extras
    groups: List[Group]
    load_more_groups: str
    total_rows_groups: int
