# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    custom_message: Optional[str] = Field(
        None, description='optional, for email invites'
    )
    email: Optional[str] = Field(
        None,
        description='required for email invites only',
        examples=['not-a-user-yet@example.com'],
    )
    expires_at: Optional[str] = Field(
        None,
        description='optional, if not supplied, the invite_expiry_days site\nsetting is used',
    )
    group_id: Optional[int] = Field(
        None, description='optional, either this or `group_names`'
    )
    group_names: Optional[str] = Field(
        None, description='optional, either this or `group_id`'
    )
    max_redemptions_allowed: Optional[int] = Field(
        1, description='optional, for link invites', examples=[5]
    )
    skip_email: Optional[bool] = False
    topic_id: Optional[int] = None


class JsonPostResponse(BaseModel):
    created_at: Optional[str] = Field(None, examples=['2021-01-01T12:00:00.000Z'])
    custom_message: Optional[str] = Field(None, examples=['Hello world!'])
    email: Optional[str] = Field(None, examples=['not-a-user-yet@example.com'])
    emailed: Optional[bool] = Field(None, examples=[False])
    expired: Optional[bool] = Field(None, examples=[False])
    expires_at: Optional[str] = Field(None, examples=['2021-02-01T12:00:00.000Z'])
    groups: Optional[List] = Field(None, examples=[[]])
    id: Optional[int] = Field(None, examples=[42])
    link: Optional[str] = Field(
        None, examples=['http://example.com/invites/9045fd767efe201ca60c6658bcf14158']
    )
    topics: Optional[List] = Field(None, examples=[[]])
    updated_at: Optional[str] = Field(None, examples=['2021-01-01T12:00:00.000Z'])
