# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Data(BaseModel):
    badge_id: Optional[int] = None
    badge_name: Optional[str] = None
    badge_slug: Optional[str] = None
    badge_title: Optional[bool] = None
    username: Optional[str] = None


class Notification(BaseModel):
    created_at: Optional[str] = None
    data: Optional[Data] = None
    id: Optional[int] = None
    notification_type: Optional[int] = None
    post_number: Optional[str] = None
    read: Optional[bool] = None
    slug: Optional[str] = None
    topic_id: Optional[int] = None
    user_id: Optional[int] = None


class JsonGetResponse(BaseModel):
    load_more_notifications: Optional[str] = None
    notifications: Optional[List[Notification]] = None
    seen_notification_id: Optional[int] = None
    total_rows_notifications: Optional[int] = None
