# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    id: Optional[int] = Field(
        None, description='(optional) Leave off to mark all notifications as\nread'
    )


class JsonPutResponse(BaseModel):
    success: Optional[str] = None
