# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ActionsSummaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    can_act: bool
    id: int


class ReplyToUser(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avatar_template: str
    name: Optional[str] = None
    username: str


class JsonGetResponseItem(BaseModel):
    actions_summary: List[ActionsSummaryItem]
    admin: bool
    avatar_template: str
    bookmarked: bool
    can_delete: bool
    can_edit: bool
    can_recover: bool
    can_view_edit_history: bool
    can_wiki: bool
    cooked: str
    created_at: str
    deleted_at: Optional[str] = None
    display_username: Optional[str] = None
    edit_reason: Optional[str] = None
    flair_bg_color: Optional[str] = None
    flair_color: Optional[str] = None
    flair_name: Optional[str] = None
    flair_url: Optional[str] = None
    hidden: bool
    id: int
    incoming_link_count: int
    moderator: bool
    name: Optional[str] = None
    post_number: int
    post_type: int
    primary_group_name: Optional[str] = None
    quote_count: int
    readers_count: int
    reads: int
    reply_count: int
    reply_to_post_number: int
    reply_to_user: ReplyToUser
    reviewable_id: Optional[str] = None
    reviewable_score_count: int
    reviewable_score_pending_count: int
    score: int
    staff: bool
    topic_id: int
    topic_slug: str
    trust_level: int
    updated_at: str
    user_deleted: bool
    user_id: int
    user_title: Optional[str] = None
    username: str
    version: int
    wiki: bool
    yours: bool


class JsonGetResponse(RootModel[List[JsonGetResponseItem]]):
    root: List[JsonGetResponseItem] = Field(..., min_length=1)
