# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class JsonPostRequest(BaseModel):
    flag_topic: Optional[bool] = None
    id: int
    post_action_type_id: int


class ActionsSummaryItem(BaseModel):
    acted: Optional[bool] = None
    can_undo: Optional[bool] = None
    count: Optional[int] = None
    id: Optional[int] = None


class JsonPostResponse(BaseModel):
    actions_summary: Optional[List[ActionsSummaryItem]] = None
    admin: Optional[bool] = None
    avatar_template: Optional[str] = None
    can_delete: Optional[bool] = None
    can_edit: Optional[bool] = None
    can_recover: Optional[bool] = None
    can_view_edit_history: Optional[bool] = None
    can_wiki: Optional[bool] = None
    cooked: Optional[str] = None
    created_at: Optional[str] = None
    deleted_at: Optional[str] = None
    display_username: Optional[str] = None
    edit_reason: Optional[str] = None
    flair_bg_color: Optional[str] = None
    flair_color: Optional[str] = None
    flair_name: Optional[str] = None
    flair_url: Optional[str] = None
    hidden: Optional[bool] = None
    id: Optional[int] = None
    incoming_link_count: Optional[int] = None
    moderator: Optional[bool] = None
    name: Optional[str] = None
    notice: Optional[Dict[str, Any]] = None
    post_number: Optional[int] = None
    post_type: Optional[int] = None
    primary_group_name: Optional[str] = None
    quote_count: Optional[int] = None
    readers_count: Optional[int] = None
    reads: Optional[int] = None
    reply_count: Optional[int] = None
    reply_to_post_number: Optional[str] = None
    reviewable_id: Optional[str] = None
    reviewable_score_count: Optional[int] = None
    reviewable_score_pending_count: Optional[int] = None
    score: Optional[float] = None
    staff: Optional[bool] = None
    topic_id: Optional[int] = None
    topic_slug: Optional[str] = None
    trust_level: Optional[int] = None
    updated_at: Optional[str] = None
    user_deleted: Optional[bool] = None
    user_id: Optional[int] = None
    user_title: Optional[str] = None
    username: Optional[str] = None
    version: Optional[int] = None
    wiki: Optional[bool] = None
    yours: Optional[bool] = None
