# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class GroupedSearchResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    can_create_topic: bool
    category_ids: List
    error: Optional[str] = None
    group_ids: List
    more_categories: Optional[str] = None
    more_full_page_results: Optional[str] = None
    more_posts: Optional[str] = None
    more_users: Optional[str] = None
    post_ids: List
    search_log_id: int
    tag_ids: List
    term: str
    user_ids: List


class JsonGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    categories: List
    grouped_search_result: GroupedSearchResult
    groups: List
    posts: List
    tags: List
    users: List
