# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Topic(BaseModel):
    category_id: Optional[int] = None
    title: Optional[str] = None


class JsonPutRequest(BaseModel):
    topic: Optional[Topic] = None


class BasicTopic(BaseModel):
    fancy_title: Optional[str] = None
    id: Optional[int] = None
    posts_count: Optional[int] = None
    slug: Optional[str] = None
    title: Optional[str] = None


class JsonPutResponse(BaseModel):
    basic_topic: Optional[BasicTopic] = None
