# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    based_on_last_post: Optional[bool] = None
    category_id: Optional[int] = None
    status_type: Optional[str] = None
    time: Optional[str] = Field(None, examples=[''])


class JsonPostResponse(BaseModel):
    based_on_last_post: Optional[bool] = None
    category_id: Optional[str] = None
    closed: Optional[bool] = None
    duration: Optional[str] = None
    execute_at: Optional[str] = None
    success: Optional[str] = Field(None, examples=['OK'])
