# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class NotificationLevel(Enum):
    field_0 = '0'
    field_1 = '1'
    field_2 = '2'
    field_3 = '3'


class JsonPostRequest(BaseModel):
    notification_level: NotificationLevel


class JsonPostResponse(BaseModel):
    success: Optional[str] = Field(None, examples=['OK'])
