# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class JsonPostRequest(BaseModel):
    email: Optional[str] = None
    user: Optional[str] = None


class User(BaseModel):
    avatar_template: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    username: Optional[str] = None


class JsonPostResponse(BaseModel):
    user: Optional[User] = None
