# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    timestamp: str = Field(..., examples=['1594291380'])


class JsonPutResponse(BaseModel):
    success: Optional[str] = Field(None, examples=['OK'])
