# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Tag(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    staff: Optional[bool] = None
    topic_count: Optional[int] = None


class Poster(BaseModel):
    description: Optional[str] = None
    extras: Optional[str] = None
    primary_group_id: Optional[str] = None
    user_id: Optional[int] = None


class Topic(BaseModel):
    archetype: Optional[str] = None
    archived: Optional[bool] = None
    bookmarked: Optional[bool] = None
    bumped: Optional[bool] = None
    bumped_at: Optional[str] = None
    category_id: Optional[int] = None
    closed: Optional[bool] = None
    created_at: Optional[str] = None
    fancy_title: Optional[str] = None
    featured_link: Optional[str] = None
    has_summary: Optional[bool] = None
    highest_post_number: Optional[int] = None
    id: Optional[int] = None
    image_url: Optional[str] = None
    last_posted_at: Optional[str] = None
    last_poster_username: Optional[str] = None
    last_read_post_number: Optional[int] = None
    like_count: Optional[int] = None
    liked: Optional[bool] = None
    notification_level: Optional[int] = None
    pinned: Optional[bool] = None
    pinned_globally: Optional[bool] = None
    posters: Optional[List[Poster]] = None
    posts_count: Optional[int] = None
    reply_count: Optional[int] = None
    slug: Optional[str] = None
    tags: Optional[List] = None
    title: Optional[str] = None
    unpinned: Optional[str] = None
    unread_posts: Optional[int] = None
    unseen: Optional[bool] = None
    views: Optional[int] = None
    visible: Optional[bool] = None


class TopicList(BaseModel):
    can_create_topic: Optional[bool] = None
    draft: Optional[str] = None
    draft_key: Optional[str] = None
    draft_sequence: Optional[int] = None
    per_page: Optional[int] = None
    tags: Optional[List[Tag]] = None
    topics: Optional[List[Topic]] = None


class User(BaseModel):
    avatar_template: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None
    username: Optional[str] = None


class JsonGetResponse(BaseModel):
    primary_groups: Optional[List] = None
    topic_list: Optional[TopicList] = None
    users: Optional[List[User]] = None
