# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Permissions(BaseModel):
    everyone: Optional[int] = None


class TagGroup(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    one_per_topic: Optional[bool] = None
    parent_tag_name: Optional[List] = None
    permissions: Optional[Permissions] = None
    tag_names: Optional[List] = None


class JsonGetResponse(BaseModel):
    tag_group: Optional[TagGroup] = None


class JsonPutRequest(BaseModel):
    name: Optional[str] = None


class JsonPutResponse(BaseModel):
    success: Optional[str] = None
    tag_group: Optional[TagGroup] = None
