# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict


class Permissions(BaseModel):
    staff: Optional[int] = None


class TagGroup(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    one_per_topic: Optional[bool] = None
    parent_tag_name: Optional[List] = None
    permissions: Optional[Permissions] = None
    tag_names: Optional[List] = None


class JsonGetResponse(BaseModel):
    tag_groups: Optional[List[TagGroup]] = None


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str


class TagGroupModel(BaseModel):
    id: int
    name: str
    one_per_topic: bool
    parent_tag_name: List
    permissions: Dict[str, Any]
    tag_names: List


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tag_group: TagGroupModel
