# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Extras(BaseModel):
    categories: Optional[List] = None


class Tag(BaseModel):
    count: Optional[int] = None
    id: Optional[str] = None
    pm_count: Optional[int] = None
    target_tag: Optional[str] = None
    text: Optional[str] = None


class JsonGetResponse(BaseModel):
    extras: Optional[Extras] = None
    tags: Optional[List[Tag]] = None
