# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    uploaded = 'uploaded'
    custom = 'custom'
    gravatar = 'gravatar'
    system = 'system'


class JsonPutRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    upload_id: int


class JsonPutResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: str = Field(..., examples=['OK'])
