# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    for_private_message: Optional[str] = Field(
        None,
        description='Optionally set this to true if the upload is for a\nprivate message.',
        examples=['true'],
    )
    for_site_setting: Optional[str] = Field(
        None,
        description='Optionally set this to true if the upload is for a\nsite setting.',
        examples=['true'],
    )
    pasted: Optional[str] = Field(
        None,
        description='Optionally set this to true if the upload was pasted\ninto the upload area. This will convert PNG files to JPEG.',
        examples=['true'],
    )
    unique_identifier: str = Field(
        ...,
        description='The unique identifier returned in the original /generate-presigned-put\nrequest.',
        examples=['66e86218-80d9-4bda-b4d5-2b6def968705'],
    )


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dominant_color: Optional[str] = None
    extension: str
    filesize: int
    height: int
    human_filesize: str
    id: int
    original_filename: str
    retain_hours: Optional[str] = None
    short_path: str
    short_url: str
    thumbnail_height: int
    thumbnail_width: int
    url: str
    width: int
