# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    avatar = 'avatar'
    profile_background = 'profile_background'
    card_background = 'card_background'
    custom_emoji = 'custom_emoji'
    composer = 'composer'


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file: Optional[Any] = None
    synchronous: Optional[bool] = Field(
        None, description='Use this flag to return an id and url'
    )
    type: Type
    user_id: Optional[int] = Field(None, description='required if uploading an avatar')


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dominant_color: Optional[str] = None
    extension: str
    filesize: int
    height: int
    human_filesize: str
    id: int
    original_filename: str
    retain_hours: Optional[str] = None
    short_path: str
    short_url: str
    thumbnail_height: int
    thumbnail_width: int
    url: str
    width: int
