# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    external_upload_identifier: str = Field(
        ...,
        description='The identifier of the multipart upload in the external\nstorage provider. This is the multipart upload_id in AWS S3.',
        examples=[
            '84x83tmxy398t3y._Q_z8CoJYVr69bE6D7f8J6Oo0434QquLFoYdGVerWFx9X5HDEI_TP_95c34n853495x35345394.d.ghQ'
        ],
    )


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    success: str = Field(..., examples=['OK'])
