# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sha1_checksum: Optional[str] = Field(
        None,
        alias='sha1-checksum',
        description='The SHA1 checksum of the upload binary blob. Optionally\nbe provided and serves as an additional security check when\nlater processing the file in complete-external-upload endpoint.',
    )


class UploadType(Enum):
    avatar = 'avatar'
    profile_background = 'profile_background'
    card_background = 'card_background'
    custom_emoji = 'custom_emoji'
    composer = 'composer'


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_name: str = Field(..., examples=['IMG_2021.jpeg'])
    file_size: int = Field(
        ..., description='File size should be represented in bytes.', examples=[4096]
    )
    metadata: Optional[Metadata] = None
    upload_type: UploadType


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    external_upload_identifier: str = Field(
        ...,
        description='The identifier of the multipart upload in the external\nstorage provider. This is the multipart upload_id in AWS S3.',
        examples=[
            '84x83tmxy398t3y._Q_z8CoJYVr69bE6D7f8J6Oo0434QquLFoYdGVerWFx9X5HDEI_TP_95c34n853495x35345394.d.ghQ'
        ],
    )
    key: str = Field(
        ...,
        description='The path of the temporary file on the external storage\nservice.',
        examples=['temp/site/uploads/default/12345/67890.jpg'],
    )
    unique_identifier: str = Field(
        ...,
        description='A unique string that identifies the external upload.\nThis must be stored and then sent in the /complete-multipart\nand /batch-presign-multipart-parts endpoints.',
        examples=['66e86218-80d9-4bda-b4d5-2b6def968705'],
    )
