# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parts: List = Field(
        ...,
        description='All of the part numbers and their corresponding ETags\nthat have been uploaded must be provided.',
        examples=[
            [
                {'etag': '0c376dcfcc2606f4335bbc732de93344', 'part_number': 1},
                {'etag': '09ert8cfcc2606f4335bbc732de91122', 'part_number': 2},
            ]
        ],
    )
    unique_identifier: str = Field(
        ...,
        description='The unique identifier returned in the original /create-multipart\nrequest.',
        examples=['66e86218-80d9-4bda-b4d5-2b6def968705'],
    )


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dominant_color: Optional[str] = None
    extension: str
    filesize: int
    height: int
    human_filesize: str
    id: int
    original_filename: str
    retain_hours: Optional[str] = None
    short_path: str
    short_url: str
    thumbnail_height: int
    thumbnail_width: int
    url: str
    width: int
