# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict, Field


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    part_numbers: List = Field(
        ...,
        description='The part numbers to generate the presigned URLs for,\nmust be between 1 and 10000.',
        examples=[[1, 2, 3]],
    )
    unique_identifier: str = Field(
        ...,
        description='The unique identifier returned in the original /create-multipart\nrequest.',
        examples=['66e86218-80d9-4bda-b4d5-2b6def968705'],
    )


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    presigned_urls: Dict[str, Any] = Field(
        ...,
        description='The presigned URLs for each part number, which has\nthe part numbers as keys.',
        examples=[
            {
                '1': 'https://discourse-martin-uploads-test.s3.us-east-2.amazonaws.com/temp/uploads/default/123abc/123abc.jpg?partNumber=1&uploadId=123456abcd&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=test&X-Amz-Date=20211222T012336Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=abc123'
            }
        ],
    )
