# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, Field


class JsonPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    active: Optional[bool] = Field(
        None,
        description='This param requires an api key in the request header\nor it will be ignored',
    )
    approved: Optional[bool] = None
    email: str
    external_ids: Optional[Dict[str, Any]] = None
    name: str
    password: str
    user_fields_1_: Optional[bool] = Field(None, alias='user_fields[1]')
    username: str


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    active: bool
    message: str
    success: bool
    user_id: Optional[int] = None
