# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class JsonPutRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    password: str
    username: str
