# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class UserAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acting_avatar_template: str
    acting_name: Optional[str] = None
    acting_user_id: int
    acting_username: str
    action_code: Optional[str] = None
    action_type: int
    archived: bool
    avatar_template: str
    category_id: int
    closed: bool
    created_at: str
    deleted: bool
    excerpt: str
    hidden: Optional[str] = None
    name: Optional[str] = None
    post_id: Optional[str] = None
    post_number: int
    post_type: Optional[str] = None
    slug: str
    target_name: Optional[str] = None
    target_user_id: int
    target_username: str
    title: str
    topic_id: int
    user_id: int
    username: str


class JsonGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_actions: List[UserAction]
