# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class JsonPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gravatar_avatar_template: Optional[str] = None
    gravatar_upload_id: Optional[int] = None
